version: "3.8"

services:
  ml-backend:
    container_name: label-studio-yolov5
    image: label-studio-yolov5
    environment:
      - MODEL_DIR=/data/models
      - WORKERS=2
      - THREADS=4
      - LOG_LEVEL=DEBUG
    ports:
      - "9090:9090"
